Добавляет разметку главной страницы
htmlacademy-htmlcss/2002115-sedona-33 pull request #2
Opened 2022-01-29 13:27 UTC by Anechua

2022-01-30 09:35 UTC, 4err requested changes
Отличная работа!

2022-01-30 09:35 UTC, 4err commented on index.html
> +        <a class="navigation-logo" href="index.html">
Мы сейчас уже находимся на странице `index.html`. Нужно избегать создания цикличных ссылок страниц на самих себя. Если элемент является ссылкой, но в какой-то момент он не является ею, потому что, например, ведет на саму себя, мы убираем ему атрибут href. Так браузер и поисковики поймут, что данный элемент, хоть сейчас и не ссылка, но когда-то он ею является.
Нужно исправить здесь и далее.

2022-01-30 09:35 UTC, 4err commented on index.html
> +            <a class="navigation-link" href="#">ХОЧУ СЮДА!</a>
Все тексты пишем по правилам русского языка. С большой буквы, остальные маленькими. Капс добавим позже с помощью стилизации. Таким образом, мы сможем не меняя код изменять стиль по необходимости.
Здесь и далее.

2022-01-30 09:35 UTC, 4err commented on index.html
> +        <section class="banner">
Поехало форматирование. Данный отступ лишний, т.к. секция и заголовок находятся на одном уровне, а не вложены друг в друга. Нужно весь код сдвинуть на уровень `h1`

2022-01-30 09:35 UTC, 4err commented on index.html
> +          <p><span class="section-description">Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</span></p>
А для чего этот спан? Мы можем повесить класс на абзац и таким образом избавиться от него. 

Здесь и далее.

2022-01-30 09:35 UTC, 4err commented on index.html
> +              <h3 class="advantages-title-white">Настоящий<br>городок</h3>
Старайся не использовать `br` в разметке. Прибегай к нему только в крайнем случае, а так все переносы делаются с помощью CSS. На данном этапе их можно все удалить и добавим уже тогда, когда будет понятно, что без них никак.

У карточек отличается не только цвет заголовка, но и всего текста и фона. Поэтому лучше назначать класс на всю обертку причины. Ниже описал подробнее.

2022-01-30 09:35 UTC, 4err commented on index.html
> +          </ul>
У блоков Жильё, еда, сувениры  и 3, 4, 5 причин другой цвет фона и текста. Да, структура и все остальные параметры похожи, поэтому следует использовать один класс. Но в таких ситуациях также следует добавить дополнительный класс, который переопределит часть свойств базового класса, например, как раз фон и шрифт.

2022-01-30 09:35 UTC, 4err commented on index.html
> +              <ul class="recomendations-list">
Сейчас получается, будто бы Жилье, еда и сувениры относятся к блоку "Настоящий городок", хотя они похожи на такие же самостоятельные причины, просто без нумерации. Их можно также внести в общий список и стилизовать как и остальные причины.

2022-01-30 09:35 UTC, 4err commented on index.html
> +          <button class="button">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
Ссылка же. По нажатию на нее, мы можем уйти на странице поиска гостиницы.

2022-01-30 09:35 UTC, 4err commented on index.html
> +      <section class="sign-up-index">
Лучше как и с причинами использовать 2 класса. Один общий и один для задания фона на главной.

2022-01-30 09:35 UTC, 4err commented on index.html
> +              <span class="visually-hidden">Twitter</span>
потерялся отступ. Здесь и далее.

2022-01-30 09:35 UTC, 4err commented on index.html
> +              <a class="button" href="https://twitter.com/htmlacademy_ru">
Нужен доп класс для указания соц сети

2022-01-30 14:06 UTC, Anechua commented on index.html
> +              <ul class="recomendations-list">
Возможно я включила режим nerd, но я вынесла Жилье, Еду и Сувениры в подсписок, поскольку обратила внимание на стиль их написания (я имею в виду не дизайн, а именно текстовую стилистику). Он отличается от того, как сформулированы пронумерованные причины посещения города:
Заголовки пронумерованных блоков и их описание написаны, скажем так, "повествовательно", в то время как заголовки непронумерованных блоков сформулированы лаконично ("жильё", "еда", "сувениры"....это не то же самое, что "красивая дорога"), а их описание по смыслу является не причиной посещения города, а рекомендациями, раскрывающими или дополняющими причину № 1, как мне показалось.

Различия в стилистике написаний этих блоков стало для меня маркером, указывающим на то, что это всё-таки разные по значению блоки. Я вижу в этом определённую логику, но если такой подход в корне неверен, то я, конечно же, исправлю.

2022-01-30 14:13 UTC, Anechua commented on index.html
> +          <button class="button">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
Насколько я поняла из макета, это не ссылка, которая ведет на страницу поиска гостиниц, а кнопка, вызывающая модальное окно на главной странице с формой параметров для поиска гостиницы. Поэтому сделала кнопкой.

Судя по макету, на страницу поиска гостиниц можно попасть из навигации в header и при нажатии кнопки "Найти" в модальном окне. Возможно у меня неверная логика..

2022-01-31 15:06 UTC, 4err commented on index.html
> +              <ul class="recomendations-list">
Обоснование принимается, давай так оставим.

2022-01-31 15:09 UTC, 4err commented on index.html
> +          <button class="button">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
Логика верная, однако, мы также должны предусмотреть возможность работы с сайтом пользователям у которых не загрузится JS или произойдет какая-то ошибка.

Есть несколько правил по выбору "ссылка" или "кнопка".
- Кнопка используется внутри формы.
- Кнопка работает в рамках одной страницы и реализует какой-то функционал. Например, переключение слайдов, увеличение картинки, выбор какого-то инструмента на панели управления итп.
Во всех остальных случаях это ссылка. Если кнопка в теории может вести на другую страницу, то это ссылка, даже если она выглядит как кнопка.

В случае с попапом бронирования. Может ли быть такое событие, что при нажатии кнопки откроется другая страница с формой, где мы ее заполним? Конечно, такое в теории возможно. Это ссылка.

На самом деле это будет позже раскрыто, но если вкратце, не всегда работают скрипты или JS у пользователя и мы должны обеспечить возможность работы даже в таком случае. И соответственно ссылка продолжает работать и переведет пользователя на страницу с формой.
Ссылку в кнопку превратить легко, а вот наоборот уже проблематично. Поэтому как правило у нас ссылки, а кнопки только в формах и функциональных элементах.

2022-01-31 15:13 UTC, Anechua commented on index.html
> +          <button class="button">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
Поняла, спасибо за развёрнутый ответ!

2022-02-01 09:04 UTC, 4err requested changes
Еще чуть чуть

2022-02-01 09:04 UTC, 4err commented on index.html
> +          <li class="advantages-item">
Так а для этих причин доп классы? У 3,4, 5 разные фоны и цвет текста по сравнению с основным.

2022-02-01 09:04 UTC, 4err commented on index.html
> +            <h3 class="advantages-title-white">Там есть мост дьявола</h3>
Мы же определились уже, что цвет текста меняется не только у заголовка, а у всего блока, поэтому данный класс можно унифицировать во все фичи, а изменения вынести в общий класс элемента `li`. Тот же, который и за фон будет отвечать.

2022-02-02 05:25 UTC, merged