Разметка страницы каталога
htmlacademy-htmlcss/2002115-sedona-33 pull request #3
Opened 2022-02-02 08:11 UTC by Anechua

2022-02-02 09:31 UTC, 4err requested changes
Отличная работа!

2022-02-02 09:31 UTC, 4err commented on catalog.html
> +            <button class="button reset-button">Сбросить</button>
Давай добавим кнопкам типы.

2022-02-02 09:31 UTC, 4err commented on catalog.html
> +          <div>
Не уверен в необходимости этих оберток дивов. У тебя вполне нормальная структура и без них. Лучше сначала размечать то, что действительно нужно, а новые обертки добавлять по мере необходимости

2022-02-02 09:31 UTC, 4err commented on catalog.html
> +            </a>
Лучше сделать две независимые ссылки, а то будут проблемы со стилизацией.

2022-02-02 09:31 UTC, 4err commented on catalog.html
> +          <div class="hotel-card">
У нас тут явно список карточек, поэтому лучше сделать через ul>li. 
Также карточки отеля вполне себе самостоятельный и могут быть использованы например, в рекламных баннерах или на других страницах, поэтому имеет смысл сделать их через `article`

2022-02-02 09:31 UTC, 4err commented on catalog.html
> +              <img src="#" alt="звезда">
Для экономии ресурсов можно заменить одним изображением.

2022-02-02 09:31 UTC, 4err commented on catalog.html
> +              <a class="pagination-link pagination-current" href="#">1</a>
href у текущей страницы.

2022-02-02 14:21 UTC, Anechua commented on catalog.html
> +              <img src="#" alt="звезда">
А что значит "для экономии ресурсов"? От этого будет медленней работать?

Просто я сделала каждую звезду отдельно, поскольку предполагаю, что когда какой-то условный администратор сайта будет заводить карточку какого-то отеля, то наверняка он будет где-то проставлять просто категорию (к примеру, "4"), а далее в карточке должно автоматически проставляться четыре звездочки. Я, конечно, вообще не представляю, как это будет работать на практике :), но мне кажется это логичным, потому что иначе нужно будет предусмотреть несколько картинок с различным количеством звезд на все случаи жизни (одна картинка - с одной звездой, другая - с двумя звездами и т.д.).

2022-02-03 08:18 UTC, 4err commented on catalog.html
> +              <img src="#" alt="звезда">
Когда сайт загружается у пользователя, браузер загружает одновременно определенное количество ресурсов. Соответственно, чтобы сайт грузился быстрее, мы хотим, чтобы эти самые ресурсы загружались быстрее и пытаемся сократить их количество. Хотя вот сейчас писал и понял, что ошибочно оставил этот комментарий, изображение то будет одно и на скорость загрузки это никак не повлияет. 

Критерия про минимальное количество элементов теперь тоже нет, так что пожалуй можно оставить и так. 
Альтернативные варианты:
- Несколько разных картинок с разным количеством звезд
- Реализация изображений фоном и ограничение количества звезд путем ограничения ширины блока и повторяющимся фоном.

2022-02-03 08:18 UTC, merged